### ISSUE TITLE
Vagrant-vbguest needed if running ubuntu?

### ISSUE THREAD

**Issue by cdorin93** [eddylackmann/Limesurvey-vagrantBox#1]
On my local machines, _vagrant up_ won't run without: _vagrant plugin install vagrant-vbguest_ . OS: ubuntu 20.04 - haven't checked in-depth the culprit. Thanks, Eddy, for sharing the script!

**Comment by eddylackmann** [comment]
If Ubuntu 20.04 required vagrant-vbguest plugin , you have to install it first! On Windows machine it will be fetched automatically.

**Comment by eddylackmann** [comment]
For Ubuntu Run "vagrant plugin update"  to update the plugin stands before running "vagrant up". 
The vbguest plugin will be automatically updated (Solved the issue ion my ubuntu machine)
